# Generated by Django 3.1 on 2020-09-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
